### ISSUE TITLE
Link to dtube not working on mixion

### ISSUE THREAD

**Issue by celizstine** [edTheGuy00/Mixion#10]
#### Expected behavior
Using the app i expected to be able to goto the dtube platform from the app using the short link feature.

#### Actual behavior
When i clicked on the short link feature for dtube, it was not responding, seems not working.

#### How to reproduce
Download the app
login with steemit details
click on menu
click on the short link to dtube

* Browser:  infinix note 4 pro
* Operating system: nougat (7.0)

#### Recording Of The Bug
https://youtu.be/uHq5ec5fqgk
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@celizstine/link-to-dtube-not-working-on-mixion">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by edTheGuy00** [comment]
This App is unreleased and this feature is not yet added. Please stop spamming this page just to get your Steem dollars.
