### ISSUE TITLE
Fatal exception when attempting to launch application

### ISSUE THREAD

**Issue by tobias-g1** [edTheGuy00/Mixion#11]
#### Expected behavior
As a user I should be able to download the application and successfully launch the application. 

#### Actual behavior
Currently, I am unable to launch the application, when I download the application from the Google Play store and locate the application within my folder I am unable to launch and it throws an exception. It states that the application has stopped working. 

#### How to reproduce
1.  Download the application using the link provided within the play store:
https://play.google.com/store/apps/details?id=com.taskail.mixion
2. Locate the application within your applications.
3. Click on the icon to launch the application.
4. The application will not launch and an exception will occur.

Note: I believe this issue is OS related and other android versions will not see this issues as per other bugs mentioned on Utopian.io.

* Browser: N/A
* Android Version: 5.0.2
* Device: Samsung Galaxy Alpha
* Model Number: SM-G850F

* Application Version: 1.0.1-beta-2

#### Recording Of The Bug

A recording of the bug can be found here: https://d.tube/#!/v/tobias-g/h68nusdp

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/fatal-exception-when-attempting-to-launch-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by edTheGuy00** [comment]
Logs needed in order to pinpoint the issue, this seems to occur on a few devices on Android 5.0
