### ISSUE TITLE
Proposal to Draft a Mixion App Privacy Policy 

### ISSUE THREAD

**Issue by Pope19** [edTheGuy00/Mixion#13]
In light of recent development and improvement with respect to __Mixion App__, i decided to navigate through the App to familiarize myself with it. 

Having done this, and based on the limit of what i saw, i discovered there wasn't a __Mixion Privacy Policy__. 

Therefore, i am proposing to draft a __Mixion Privacy Policy__ which will be submitted in the __Pull request__. , 

The draft will be subject to your criticism and suggestions. 

Please, your response in this regard is highly anticipated.

@pope1995

**Comment by edTheGuy00** [comment]
https://github.com/edTheGuy00/Mixion/blob/master/privacy_policy.html
