### ISSUE TITLE
Promotion of mixion

### ISSUE THREAD

**Issue by edikanefanga** [edTheGuy00/Mixion#14]
Good day, I just downloaded the mixion app some days ago and with what I have seen so far its a very good app that has come to stay. But most people don't know about this application due to poor exposure. So I wanted to ask it I could advertise the mixion adroid app on Facebook using Facebook ads. Your permission is required for me to go ahead with the advert.

**Comment by edTheGuy00** [comment]
I don't thinks that's a good Idea just now. This app is still in beta and there are lots of features missing. Maybe when all features are added and all features are added you can promote it, but not now.
