### ISSUE TITLE
Donate button not working on mixion

### ISSUE THREAD

**Issue by celizstine** [edTheGuy00/Mixion#5]
#### Expected behavior
after logging in the app, i wanted to donate to the project for support to increase the development on it.

#### Actual behavior
But when i clicked on donation button, it was not responding.

#### How to reproduce
download mixion app
login in with their steemit details
click on donate button

* Browser: infinix note 4 pro
* Operating system: nougat

#### Recording Of The Bug
https://youtu.be/Kf-XhJCOvUk
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@celizstine/donate-button-not-working-on-mixion">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by edTheGuy00** [comment]
This App is unreleased and this feature is not yet added. Please stop spamming this page just to get your Steem dollars.

**Comment by celizstine** [comment]
well thanks. Was about suggesting a draft feature, just found out. Will
stay of your projects. Sorry for contributing to it.

**Comment by edTheGuy00** [comment]
I don't mind useful submission of bugs, crashes, weird behavior or even suggestions. But opening an issue for every single button or feature that doesn't work is annoying. This app is in pre-release Beta, so of course some things will not work because it is still incomplete

**Comment by celizstine** [comment]
Oh.... Am really sorry about that. We combine my contributions next time.
Thanks for responding.
