### ISSUE TITLE
Link feature not working

### ISSUE THREAD

**Issue by celizstine** [edTheGuy00/Mixion#6]
#### Expected behavior
when writing a post i expected to be able to use the insert link function to reference my work

#### Actual behavior
when i clicked on the insert link function, the feature dont respond, meaning its not working.

#### How to reproduce
download mixion app
login with steemit details
click on add button to make a post
click on insert link option below

* Browser: infinix note 4 pro
* Operating system: nougat

#### Recording Of The Bug
https://youtu.be/Fl0dU7I-k2E

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@celizstine/link-feature-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by edTheGuy00** [comment]
This App is unreleased and this feature is not yet added. Please stop spamming this page just to get your Steem dollars.
