### ISSUE TITLE
Preview feature not working

### ISSUE THREAD

**Issue by celizstine** [edTheGuy00/Mixion#7]
#### Expected behavior
When making a post i expect to be able preview what am writing to make sure my markdown is correct and the rest

#### Actual behavior
I tried to use the preview feature but its not working

#### How to reproduce
download the app
login with steemit details
click the plus sign to make a post
click the eye logo above to make post
hold down for preview to pop up
click it to preview

* Browser:  infinix note 4b pro
* Operating system:nougat

a video to reproduce
https://youtu.be/s-jLkqQHVlE
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@celizstine/preview-feature-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by edTheGuy00** [comment]
This App is unreleased and this feature is not yet added. Please stop spamming this page just to get your Steem dollars.
