### ISSUE TITLE
Clicking on "Powered by AskMe" in SearchView Activity Opens details of Post on the Home Activity

### ISSUE THREAD

**Issue by mathemandy** [edTheGuy00/Mixion#8]
Mixion App is A native Android app for Steemit.com and can be downloaded on [playstore](https://play.google.com/store/apps/details?id=com.taskail.mixion) 
#### Expected behavior
When i clicked on the AskmeLogo. i was hoping to learn more about the logo or nothing shoud really happen. d.tube.com has the same logo when you make a search. Clicking on this logo takes you to https://www.asksteem.com/.

#### Actual behavior
When i clicked on the AskSteem Logo, it opened the details of the post at the position of the screen. I tried clicking every other part of the screen but nothing happened. This reduces user Experience.
#### How to reproduce
- Open Mixion App and wait for all Feed to Load
- Click on the Search Icon on the Mixion App 
![mixion_seac.jpeg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520279377/iphtpyvhqzmht6wzekw9.jpg)
- Click on the Logo area as shown below and it should open the details of the post 
![mixion_aks.jpeg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520280014/gtae9vukxkvyhshcl9ym.jpg)

- Press back , click the bottom area of the screen, nothing happens 

* Phone: Infinix Note 4 
* Operating system: Android Nougat
#### Recording of Expected Behavior
https://youtu.be/kJUNGhuSKyo
#### Recording Of The Bug
https://youtu.be/6KGGKms9sQU
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mathemandy/clicking-on-powered-by-askme-in-searchview-activity-opens-details-of-post-on-the-home-activity">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by edTheGuy00** [comment]
Reference to [this line](https://github.com/edTheGuy00/Mixion/blob/12e0270d3a52997a4369734e0d8703cd959dec9f/app/src/main/java/com/taskail/mixion/search/SearchFragment.kt#L50)
