### ISSUE TITLE
Link to dmania not working

### ISSUE THREAD

**Issue by celizstine** [edTheGuy00/Mixion#9]
#### Expected behavior
Seeing the short cut link feature to dmania was looking good so i decided to use it, so i expected to open it and find myself in dmania site.

#### Actual behavior
While clicking the feature it refused to work, like the dmania feature is not working.

#### How to reproduce
download the app 
login with steemit details
click on menu
click on short link to dmania

* Browser:  infinix note 4
* Operating system: nougat

#### Recording Of The Bug
https://youtu.be/PzD5TBGWmAw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@celizstine/link-to-dmania-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by edTheGuy00** [comment]
This App is unreleased and this feature is not yet added. Please stop spamming this page just to get your Steem dollars.
